### ISSUE TITLE
with CRM online not working.

### ISSUE THREAD

**Issue by rrizwann** [lucasalexander/Crm-Sample-Code#1]
HI 

I have tried to run the same thing with CRM 2016 online and create directory for azure oauth 2.0
now I am unable to get the access_token from azure machine

getting error in this lines
var reqPost = https.request(options, function(resPost) {
    //log headers and post string
    console.log("headers: ", resPost.headers);
    console.log("formvals: ", formvals);

    //set up the event handler for when we get a response
    resPost.on('data', function(d) {
      //parse the response to extract the token
	  console.log('dada');
      var json = JSON.parse(d);

      //log it
      console.log('token response: ' + json);

      //if we get an error, show it to the client
      if(json.error) {
        res.write(json.error);
      }
      else {
      //no error, so let's store the token values in a session cookie
        sess.access_token=json.access_token;
        sess.refresh_token=json.refresh_token;

**Comment by lucasalexander** [comment]
Sorry, this could be a number of things, and I don't have a way to effectively support issues that arise from my sample code.
